FROM php:7.1-apache

ENV APACHE_DOCUMENT_ROOT /var/www/html/Demo
COPY Demo /var/www/html/Demo
COPY Wafl /var/www/html/
COPY Autoloader.php /var/www/html/

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf