<?php
namespace Wafl\Syrup;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-04 at 06:48:00.
 */
class ParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Parser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		require_once(__DIR__.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."Autoloader.php");
        $this->object = new Parser(file_get_contents(__DIR__.DIRECTORY_SEPARATOR."ParserTest.syrp"));
    }

    /**
     * Test the Parse() method
     * Generated from @assert () == \DblEj\Tests\ExpectedResults\Syrp::GetExpectedTest1Output().
     *
     * @covers Wafl\Syrup\Parser::Parse
     */
    public function testParse()
    {
        $expectedResult = unserialize(file_get_contents(__DIR__.DIRECTORY_SEPARATOR."ParserTest_Expected.bin"));
        $this->assertEquals($expectedResult,$this->object->Parse());
    }
}
