<?php

namespace Wafl\Syrup;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-04 at 06:48:00.
 */
class ValidatorTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var Validator
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Validator();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }
}
